# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTSzqQv-xt0vbI7OKUJ7SK0AUWK2Zr_d
"""

import os, glob

for file in glob.glob("*.txt"):
  os.rename(file, file + ".locked")